[add link]
redteaming-arena/redteam-arena pull request #23
Opened 2024-09-22 23:17 UTC by aangelopoulos

2024-09-22 23:19 UTC, infwinston requested changes
@aangelopoulos thanks LGTM except for config change

2024-09-22 23:19 UTC, infwinston commented on backend/app/core/config.py
> +    ALLOWED_ORIGINS: list = ["*"]#["https://www.redarena.ai", "https://redarena.ai", "http://redarena.ai"]
roll back?

2024-09-22 23:26 UTC, aangelopoulos commented
Will do... actually will quickly try to automate so we don't have to worry about this anymore.

2024-09-22 23:32 UTC, infwinston commented
maybe we can enable some local dev mode which will automatically assign `ALLOWED_ORIGINS=["*"]`

2024-09-22 23:38 UTC, aangelopoulos commented
It will be easy with the .env file :)

2024-09-23 05:15 UTC, infwinston approved these changes

2024-09-23 05:16 UTC, merged